### ISSUE TITLE
Main Content not load

### ISSUE THREAD

**Issue by hardik2419** [hryvinskyi/magento2-quickview#10]
We don't load Product title, price etc in EE.

**Comment by scriptua** [comment]
@hardik2419 I can not reproduce this issue

**Comment by scriptua** [comment]
@hardik2419 I tested on Magento EE 2.2.4

**Comment by aartipatel6495** [comment]
Currently, I am using Magento 2.3.1 enterprise version and try to install this module through composer but get an error as it is required 5.6 PHP version and Magento 2.3.1 required 7.1+

I have tried to install the module using git clone but there is some base module is missing.

So, How I can install this module? please advise

**Comment by hryvinskyi** [comment]
Try installing the module https://github.com/hryvinskyi/magento2-base

**Comment by aartipatel6495** [comment]
Hello,

https://github.com/hryvinskyi/magento2-base this module is different.

I need Script_Base  this module because I am getting below error when
clicking on quick view button from catalog listing page.

[image: image.png]

Please advise.

**Comment by hryvinskyi** [comment]
use https://github.com/hryvinskyi/magento2-base/tree/v1.1.2 this tag

**Comment by aartipatel6495** [comment]
Hello,

In https://github.com/hryvinskyi/magento2-base/tree/v1.1.2 this module
there is no any HTMl helper file and in quickview some template file
include HTML helper

Getting below error:
Fatal error: Uncaught Error: Class 'Script\Base\Helper\Html' not found in
/var/www/html/flemings/app/code/Script/QuickView/view/frontend/templates/product/view/gallery.phtml:17
Stack trace: #0
/var/www/html/flemings/vendor/magento/framework/View/TemplateEngine/Php.php(59):
include() #1
/var/www/html/flemings/vendor/magento/framework/View/Element/Template.php(271):
Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Gallery\Interceptor),
'/var/www/html/f...', Array) #2
/var/www/html/flemings/generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php(505):
Magento\Framework\View\Element\Template->fetchView('/var/www/html/f...') #3
/var/www/html/flemings/vendor/magento/framework/View/Element/Template.php(301):
Magento\Catalog\Block\Product\View\Gallery\Interceptor->fetchView('/var/www/html/f...')
#4
/var/www/html/flemings/vendor/magento/framework/View/Element/AbstractBlock.php(668):
Magento\Framework\View\Element\Template->_toHtml() #5
/var/www/html/flemings/generated/co in
/var/www/html/flemings/app/code/Script/QuickView/view/frontend/templates/product/view/gallery.phtml
on
line 17
