### ISSUE TITLE
Button not displaying on frontend

### ISSUE THREAD

**Issue by magejunkie** [hryvinskyi/magento2-quickview#13]
Module is enabled and all, correct css selector selected as well, but wont show on frontend.

Magento ver. 2.2.3

**Comment by magejunkie** [comment]
?

**Comment by hryvinskyi** [comment]
@magejunkie I tested on magento 2.2.3, I did not see this problem

**Comment by magejunkie** [comment]
I have tried to switch to default Luma theme but still the button wont work. I have attached Plugin settings screenshot. Let me know if something is wrong in it

![image](https://user-images.githubusercontent.com/3909243/44284151-76721100-a215-11e8-84dd-3078ff56cd3c.png)
